apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: edward-ciggaar-nextjs-app
  app.kubernetes.io/instance: edward-ciggaar-nextjs-app-instance
  app.kubernetes.io/name: edward-ciggaar-nextjs-app
